# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Jewelry Builder App"
client_id = "1944e3d11fe47b32b49a0e4560c2c1f4"
application_url = "https://jewelrybuilderapp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [
  "https://jewelrybuilderapp.com/auth/callback",
  "https://jewelrybuilderapp.com/auth/shopify/callback",
  "https://jewelrybuilderapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://jewelrybuilderapp.com/"
subpath = "jewelry-builder-app"
prefix = "apps"

[pos]
embedded = false
